### ISSUE TITLE
TODO prior first release, if it will be released

### ISSUE THREAD

**Issue by broeder-j** [Materials-Data-Science-and-Informatics/awesome-fair-data#2]
- [x] Add table of content
- [x] Add fair principle picture
- [x] Add connection to other awesome lists
- [x] This license or CC-4 international?
- [x] Sort alphabetical
- [x] How to contribute, i.e. allow also to write emails say contributions are welcome
- [x] Clear this inside HMC
- [x] Overwork layout if needed

This list needs to be 30 days online prior it can be included inside
